// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // But we want to explicitly define it for better control
  moduleSidebar: [
    {
      type: 'category',
      label: 'Module 1',
      link: {
        type: 'generated-index',
        description: 'ROS 2 Basics for AI-Native applications.'
      },
      items: [{type: 'autogenerated', dirName: 'module-1'}],
    },
    {
      type: 'category',
      label: 'Module 2',
      link: {
        type: 'generated-index',
        description: 'Learn about Digital Twin environments.'
      },
      items: [{type: 'autogenerated', dirName: 'module-2'}],
    },
    {
      type: 'category',
      label: 'Module 3',
      link: {
        type: 'generated-index',
        description: 'Learn about the AI-Robot Brain with NVIDIA Isaac.'
      },
      items: [{type: 'autogenerated', dirName: 'module-3'}],
    },
  ],
};

export default sidebars;